### ISSUE TITLE
Missing paper (Towards Cross-Tokenizer Distillation: the Universal Logit Distillation Loss for LLMs)

### ISSUE THREAD

**Issue by Nicolas-BZRD** [Tebmer/Awesome-Knowledge-Distillation-of-LLMs#4]
Hy guys, thanks for this great initiative. We recently release a new papers paving the way to a new method to distil any LLM to any other. I thing it could be very useful to add the paper on the list. Feel free to ask me any questions if needed. 

Paper (Towards Cross-Tokenizer Distillation: the Universal Logit Distillation Loss for LLMs): https://arxiv.org/abs/2402.12030

**Comment by Tebmer** [comment]
Great work! Thanks. We have added it :) and will update paper in a future version.
