### ISSUE TITLE
[One paper] A new way to perform KD (verified on BERT compression)

### ISSUE THREAD

**Issue by wutaiqiang** [Tebmer/Awesome-Knowledge-Distillation-of-LLMs#6]
Thanks for the great work!
I want to recommend a new method to perform KD: inherited weight. 

Name: Weight-Inherited Distillation for Task-Agnostic BERT Compression
code: https://github.com/wutaiqiang/WID-NAACL2024
Blog: https://zhuanlan.zhihu.com/p/687294843
TL, DR: 使用权重继承的思路来实现模型压缩, 直接学习一个映射，将教师模型的权重映射到学生模型。

This method is not proposed for LLM  and is evaluated on BERT compression. But may inspire readers to consider a new way to perform distillation. Thanks~

**Comment by Tebmer** [comment]
Great work! 

Thanks. We have added it and will update paper in a future version :)

**Comment by wutaiqiang** [comment]
Thanks~
