### ISSUE TITLE
Further distillation papers to consider

### ISSUE THREAD

**Issue by begab** [Tebmer/Awesome-Knowledge-Distillation-of-LLMs#7]
Thanks for the great repo, these additional papers related to masked latent semantic modeling (in which pre-training is achieved by recovering latent semantic information extracted from a teacher model) might fit the scope of the survey as well:
* [Masked Latent Semantic Modeling: an Efficient Pre-training Alternative to Masked Language Modeling](https://aclanthology.org/2023.findings-acl.876.pdf)
* [Better Together: Jointly Using Masked Latent Semantic Modeling and Masked Language Modeling for Sample Efficient Pre-training](https://aclanthology.org/2023.conll-babylm.26.pdf)

**Comment by Tebmer** [comment]
Great work! Thanks! We have added them into the repo :)
